# Generated by Django 5.0.14 on 2025-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_maps', 'Pode criar mapas de estudos'), ('can_edit_maps', 'Pode editar mapas de estudos'), ('can_export_maps', 'Pode exportar mapas de estudos')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Define se o usuário tem permissões de administrador do sistema', verbose_name='Administrador'),
        ),
    ]
