# Generated by Django 5.0.14 on 2025-10-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome da disciplina (ex: Direito Constitucional)', max_length=200, unique=True, verbose_name='Nome')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da disciplina', verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, help_text='Define se a disciplina está ativa no sistema', verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome do assunto', max_length=300, verbose_name='Nome')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do assunto dentro da disciplina', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o assunto está ativo no sistema', verbose_name='Ativo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='core.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
                'ordering': ['disciplina', 'ordem', 'nome'],
                'unique_together': {('disciplina', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Subassunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome do subassunto', max_length=400, verbose_name='Nome')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do subassunto dentro do assunto', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o subassunto está ativo no sistema', verbose_name='Ativo')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subassuntos', to='core.assunto', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Subassunto',
                'verbose_name_plural': 'Subassuntos',
                'ordering': ['assunto', 'ordem', 'nome'],
                'unique_together': {('assunto', 'nome')},
            },
        ),
    ]
