# Generated by Django 5.0.14 on 2025-10-24 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome completo do concurso (ex: TRF 2ª Região 2025)', max_length=200, verbose_name='Nome')),
                ('sigla', models.CharField(help_text='Sigla do concurso (ex: TRF, PF, PCDF)', max_length=50, verbose_name='Sigla')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do concurso', verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('GRAD', 'Graduação'), ('POS', 'Pós-graduação')], default='GRAD', help_text='Tipo do concurso', max_length=4, verbose_name='Tipo')),
                ('cursinho', models.CharField(blank=True, help_text='Nome do cursinho associado (ex: Gran Cursos, Estratégia)', max_length=100, verbose_name='Cursinho')),
                ('ativo', models.BooleanField(default=True, help_text='Define se o concurso está ativo no sistema', verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['ordem', '-created_at'],
                'unique_together': {('nome', 'sigla')},
            },
        ),
        migrations.CreateModel(
            name='MapaAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no mapa do concurso', verbose_name='Ordem')),
                ('item_edital', models.CharField(blank=True, help_text='Referência ao item do edital (ex: 3.2, 4.1.2)', max_length=100, verbose_name='Item do Edital')),
                ('extra_cursinho', models.BooleanField(default=False, help_text='Indica se é um assunto específico do cursinho, não presente na matriz', verbose_name='Assunto Extra')),
                ('nome_extra', models.CharField(blank=True, help_text='Nome do assunto extra (apenas se extra_cursinho=True)', max_length=300, verbose_name='Nome do Assunto Extra')),
                ('assunto', models.ForeignKey(blank=True, help_text='Assunto da matriz (null se for assunto extra)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='core.assunto', verbose_name='Assunto')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapa_assuntos', to='core.concurso', verbose_name='Concurso')),
                ('subassunto', models.ForeignKey(blank=True, help_text='Subassunto específico (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='core.subassunto', verbose_name='Subassunto')),
            ],
            options={
                'verbose_name': 'Mapa de Assunto',
                'verbose_name_plural': 'Mapas de Assuntos',
                'ordering': ['concurso', 'ordem'],
                'unique_together': {('concurso', 'assunto', 'subassunto')},
            },
        ),
        migrations.CreateModel(
            name='MetadadosAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('link_teoria', models.CharField(blank=True, help_text='Link para material teórico (máx. 500 caracteres)', max_length=500, verbose_name='Link Teoria')),
                ('link_resumos', models.CharField(blank=True, help_text='Link para resumos (máx. 500 caracteres)', max_length=500, verbose_name='Link Resumos')),
                ('link_questoes', models.CharField(blank=True, help_text='Link para questões (máx. 500 caracteres)', max_length=500, verbose_name='Link Questões')),
                ('link_revisoes', models.CharField(blank=True, help_text='Link para revisões (máx. 500 caracteres)', max_length=500, verbose_name='Link Revisões')),
                ('tempo_estimado', models.PositiveIntegerField(default=0, help_text='Tempo estimado de estudo em minutos', verbose_name='Tempo Estimado (minutos)')),
                ('paginas_estimadas', models.PositiveIntegerField(default=0, help_text='Número estimado de páginas', verbose_name='Páginas Estimadas')),
                ('peso_resumos', models.PositiveSmallIntegerField(default=1, help_text='Peso de importância para resumos (1 a 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Peso Resumos')),
                ('peso_questoes', models.PositiveSmallIntegerField(default=1, help_text='Peso de importância para questões (1 a 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Peso Questões')),
                ('peso_revisao', models.PositiveSmallIntegerField(default=1, help_text='Peso de importância para revisão (1 a 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Peso Revisão')),
                ('suplementar', models.BooleanField(default=False, help_text='Define se o assunto é suplementar (0=Não, 1=Sim)', verbose_name='Suplementar')),
                ('dicas', models.TextField(blank=True, help_text='Dicas e observações sobre o assunto (máx. 500 caracteres)', max_length=500, verbose_name='Dicas')),
                ('referencias', models.TextField(blank=True, help_text='Referências extras (máx. 500 caracteres)', max_length=500, verbose_name='Referências')),
                ('mapa_assunto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadados', to='core.mapaassunto', verbose_name='Mapa de Assunto')),
            ],
            options={
                'verbose_name': 'Metadados do Assunto',
                'verbose_name_plural': 'Metadados dos Assuntos',
            },
        ),
    ]
