# Generated by Django 5.0.14 on 2025-12-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_concurso_mapaassunto_metadadosassunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='dica',
            field=models.TextField(blank=True, help_text='Dica sobre o assunto (máx. 500 caracteres)', max_length=500, verbose_name='Dica'),
        ),
        migrations.AddField(
            model_name='assunto',
            name='link_questoes_cebraspe',
            field=models.CharField(blank=True, help_text='Link para caderno de questões Cebraspe', max_length=500, verbose_name='Caderno TEC Concursos - Cebraspe'),
        ),
        migrations.AddField(
            model_name='assunto',
            name='link_questoes_fgv',
            field=models.CharField(blank=True, help_text='Link para caderno de questões FGV', max_length=500, verbose_name='Caderno de Questões FGV'),
        ),
        migrations.AddField(
            model_name='assunto',
            name='link_resumos',
            field=models.CharField(blank=True, help_text='Link para aula dos Resumos OneNote', max_length=500, verbose_name='Aula dos Resumos OneNote'),
        ),
    ]
