# Generated by Django 5.0.14 on 2025-12-18 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_metadados_to_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='dicas',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='link_resumos',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='link_revisoes',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='link_teoria',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='paginas_estimadas',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='peso_revisao',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='referencias',
        ),
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='tempo_estimado',
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='dica',
            field=models.TextField(blank=True, help_text='Dica geral sobre o assunto (máx. 500 caracteres)', max_length=500, verbose_name='Dica'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='dica_questoes',
            field=models.TextField(blank=True, help_text='Dica específica para questões (máx. 500 caracteres)', max_length=500, verbose_name='Dica de Questões'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='dica_revisoes',
            field=models.TextField(blank=True, help_text='Dica específica para revisões (máx. 500 caracteres)', max_length=500, verbose_name='Dica de Revisões'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='link_estudo',
            field=models.CharField(blank=True, help_text='Link para material de estudo (máx. 500 caracteres)', max_length=500, verbose_name='Link de Estudo'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='link_resumo',
            field=models.CharField(blank=True, help_text='Link para resumos (máx. 500 caracteres)', max_length=500, verbose_name='Link de Resumo'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='minutos_calma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tempo no modo calma', max_digits=6, verbose_name='Minutos Calma'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='minutos_expresso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tempo no modo expresso', max_digits=6, verbose_name='Minutos Expresso'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='minutos_regular',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tempo no modo regular', max_digits=6, verbose_name='Minutos Regular'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='numero_questoes',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de questões recomendadas', verbose_name='Número de Questões'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='paginas_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Páginas ou minutos de vídeo para estudo', verbose_name='Páginas ou Minutos de Vídeo'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='peso_revisoes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Peso de importância para revisões (1 a 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Peso de Revisões'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='referencia',
            field=models.TextField(blank=True, help_text='Referências extras (máx. 500 caracteres)', max_length=500, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='metadadosassunto',
            name='link_questoes',
            field=models.CharField(blank=True, help_text='Link para questões (máx. 500 caracteres)', max_length=500, verbose_name='Link de Questões'),
        ),
        migrations.AlterField(
            model_name='metadadosassunto',
            name='peso_questoes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Peso de importância para questões (1 a 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Peso de Questões'),
        ),
        migrations.AlterField(
            model_name='metadadosassunto',
            name='peso_resumos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Peso de importância para resumos (1 a 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Peso de Resumos'),
        ),
    ]
