# Generated by Django 5.0.14 on 2025-12-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_metadados_tutory_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadadosassunto',
            name='link_estudo',
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='link_direcao',
            field=models.CharField(blank=True, help_text='Link para material do Direção Concursos', max_length=500, verbose_name='Link Direção'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='link_estrategia',
            field=models.CharField(blank=True, help_text='Link para material do Estratégia Concursos', max_length=500, verbose_name='Link Estratégia'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='link_pdf',
            field=models.CharField(blank=True, help_text='Link para PDF do material', max_length=500, verbose_name='Link PDF'),
        ),
        migrations.AddField(
            model_name='metadadosassunto',
            name='link_video',
            field=models.CharField(blank=True, help_text='Link para vídeo-aula', max_length=500, verbose_name='Link Vídeo'),
        ),
        migrations.AlterField(
            model_name='metadadosassunto',
            name='link_questoes',
            field=models.CharField(blank=True, help_text='Link para questões', max_length=500, verbose_name='Link de Questões'),
        ),
        migrations.AlterField(
            model_name='metadadosassunto',
            name='link_resumo',
            field=models.CharField(blank=True, help_text='Link para resumos', max_length=500, verbose_name='Link de Resumo'),
        ),
    ]
