# Generated by Django 5.0.14 on 2025-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_links_cursinhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadadosassunto',
            name='relevancia',
            field=models.CharField(choices=[('muito_alta', 'Muito Alta'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa'), ('muito_baixa', 'Muito Baixa')], default='media', help_text='Relevância do assunto para este concurso', max_length=20, verbose_name='Relevância'),
        ),
    ]
