# Generated by Django 5.0.14 on 2025-12-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_relevancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='dica',
            field=models.TextField(blank=True, help_text='Dica sobre o assunto', max_length=2000, verbose_name='Dica'),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='link_questoes_cebraspe',
            field=models.CharField(blank=True, help_text='Link para caderno de questões Cebraspe', max_length=2000, verbose_name='Caderno TEC Concursos - Cebraspe'),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='link_questoes_fgv',
            field=models.CharField(blank=True, help_text='Link para caderno de questões FGV', max_length=2000, verbose_name='Caderno de Questões FGV'),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='link_resumos',
            field=models.CharField(blank=True, help_text='Link para aula dos Resumos OneNote', max_length=2000, verbose_name='Aula dos Resumos OneNote'),
        ),
    ]
