# Generated by Django 5.0.14 on 2026-01-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_field_lengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estudado', models.BooleanField(default=False, help_text='Indica se o assunto foi marcado como estudado', verbose_name='Estudado')),
                ('tempo_total_minutos', models.PositiveIntegerField(default=0, help_text='Tempo total de estudo em minutos', verbose_name='Tempo Total (minutos)')),
                ('questoes_feitas', models.PositiveIntegerField(default=0, help_text='Total de questões feitas', verbose_name='Questões Feitas')),
                ('questoes_acertadas', models.PositiveIntegerField(default=0, help_text='Total de questões acertadas', verbose_name='Questões Acertadas')),
                ('ultima_sessao', models.DateField(blank=True, help_text='Data da última sessão de estudo', null=True, verbose_name='Última Sessão')),
                ('mapa_assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='core.mapaassunto', verbose_name='Assunto do Mapa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso do Assunto',
                'verbose_name_plural': 'Progressos dos Assuntos',
                'ordering': ['-ultima_sessao', '-updated_at'],
                'unique_together': {('usuario', 'mapa_assunto')},
            },
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data', models.DateField(help_text='Data da sessão de estudo', verbose_name='Data')),
                ('tempo_minutos', models.PositiveIntegerField(default=0, help_text='Tempo estudado nesta sessão em minutos', verbose_name='Tempo (minutos)')),
                ('questoes_feitas', models.PositiveIntegerField(default=0, help_text='Questões feitas nesta sessão', verbose_name='Questões Feitas')),
                ('questoes_acertadas', models.PositiveIntegerField(default=0, help_text='Questões acertadas nesta sessão', verbose_name='Questões Acertadas')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a sessão de estudo', verbose_name='Observações')),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.progressoassunto', verbose_name='Progresso')),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
