# Generated by Django 5.0.14 on 2026-01-06 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_progressoassunto_sessaoestudo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Se este é o plano ativo do aluno', verbose_name='Ativo')),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data em que o aluno começou o plano', verbose_name='Data de Início')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.concurso', verbose_name='Concurso/Plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Plano do Aluno',
                'verbose_name_plural': 'Planos dos Alunos',
                'ordering': ['-ativo', '-data_inicio'],
                'unique_together': {('usuario', 'concurso')},
            },
        ),
    ]
